[package]
name = "sbb-telegram-bot"
version = "0.1.0"
authors = ["Jan Nils Ferner <jn_ferner@hotmail.de>", "Lukas Hunziker <lucuhu@gmail.com>"]

[dependencies]
iron = "0.5"
router = "0.5"
serde = "1"
serde_json = "1"
serde_derive = "1"
reqwest = "0.6"
dotenv = "0.10"
maplit = "0.1.4"
